-- DROP SCHEMA admin_platform;

CREATE SCHEMA admin_platform AUTHORIZATION postgres;

-- DROP TYPE admin_platform."admin_user_role_enum";

CREATE TYPE admin_platform."admin_user_role_enum" AS ENUM (
	'admin',
	'soporte');

-- DROP TYPE admin_platform."admin_user_status_enum";

CREATE TYPE admin_platform."admin_user_status_enum" AS ENUM (
	'activo',
	'inactivo',
	'bloqueado');

-- DROP TYPE admin_platform.ciclo_facturacion_enum;

CREATE TYPE admin_platform.ciclo_facturacion_enum AS ENUM (
	'mensual',
	'trimestral',
	'anual');

-- DROP TYPE admin_platform.estado_factura_tenant_enum;

CREATE TYPE admin_platform.estado_factura_tenant_enum AS ENUM (
	'pendiente',
	'pagada',
	'vencida',
	'anulada');

-- DROP TYPE admin_platform.estado_pago_tenant_enum;

CREATE TYPE admin_platform.estado_pago_tenant_enum AS ENUM (
	'aprobado',
	'pendiente',
	'fallido',
	'reembolsado');

-- DROP TYPE admin_platform.tenant_billing_status_enum;

CREATE TYPE admin_platform.tenant_billing_status_enum AS ENUM (
	'active',
	'trialing',
	'past_due',
	'unpaid',
	'paused',
	'canceled',
	'incomplete',
	'incomplete_expired');

-- DROP SEQUENCE admin_platform.admin_users_id_seq;

CREATE SEQUENCE admin_platform.admin_users_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE admin_platform.admin_users_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE admin_platform.admin_users_id_seq TO postgres;

-- DROP SEQUENCE admin_platform.facturas_tenants_id_seq;

CREATE SEQUENCE admin_platform.facturas_tenants_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE admin_platform.facturas_tenants_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE admin_platform.facturas_tenants_id_seq TO postgres;

-- DROP SEQUENCE admin_platform.pagos_tenants_id_seq;

CREATE SEQUENCE admin_platform.pagos_tenants_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE admin_platform.pagos_tenants_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE admin_platform.pagos_tenants_id_seq TO postgres;

-- DROP SEQUENCE admin_platform.planes_suscripcion_id_seq;

CREATE SEQUENCE admin_platform.planes_suscripcion_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE admin_platform.planes_suscripcion_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE admin_platform.planes_suscripcion_id_seq TO postgres;

-- DROP SEQUENCE admin_platform.suscripciones_tenants_id_seq;

CREATE SEQUENCE admin_platform.suscripciones_tenants_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE admin_platform.suscripciones_tenants_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE admin_platform.suscripciones_tenants_id_seq TO postgres;

-- DROP SEQUENCE admin_platform.tenants_id_seq;

CREATE SEQUENCE admin_platform.tenants_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE admin_platform.tenants_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE admin_platform.tenants_id_seq TO postgres;
-- admin_platform.admin_users definition

-- Drop table

-- DROP TABLE admin_platform.admin_users;

CREATE TABLE admin_platform.admin_users ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, nombre text NOT NULL, correo text NOT NULL, telefono text NULL, passwordhash text NOT NULL, rol admin_platform."admin_user_role_enum" DEFAULT 'admin'::admin_platform.admin_user_role_enum NOT NULL, estado admin_platform."admin_user_status_enum" DEFAULT 'activo'::admin_platform.admin_user_status_enum NOT NULL, ultimo_ingreso timestamp NULL, fecha_creacion timestamp DEFAULT now() NOT NULL, fecha_actualizacion timestamp DEFAULT now() NOT NULL, CONSTRAINT admin_users_pkey PRIMARY KEY (id));
CREATE UNIQUE INDEX ux_admin_users_correo_lower ON admin_platform.admin_users USING btree (lower(correo));

-- Table Triggers

create trigger set_updated_at_admin_users before
update
    on
    admin_platform.admin_users for each row execute function admin_platform.tg_admin_users_updated_at();

-- Permissions

ALTER TABLE admin_platform.admin_users OWNER TO postgres;
GRANT ALL ON TABLE admin_platform.admin_users TO postgres;


-- admin_platform.planes_suscripcion definition

-- Drop table

-- DROP TABLE admin_platform.planes_suscripcion;

CREATE TABLE admin_platform.planes_suscripcion ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, nombre text NOT NULL, codigo text NOT NULL, descripcion text NULL, precio_mensual numeric(12, 2) DEFAULT 0 NOT NULL, precio_trimestral numeric(12, 2) DEFAULT 0 NOT NULL, precio_anual numeric(12, 2) DEFAULT 0 NOT NULL, moneda text DEFAULT 'COP'::text NOT NULL, activo bool DEFAULT true NOT NULL, fecha_creacion timestamptz DEFAULT now() NOT NULL, fecha_actualizacion timestamptz DEFAULT now() NOT NULL, CONSTRAINT chk_planes_precios_non_negative CHECK (((precio_mensual >= (0)::numeric) AND (precio_trimestral >= (0)::numeric) AND (precio_anual >= (0)::numeric))), CONSTRAINT planes_suscripcion_codigo_key UNIQUE (codigo), CONSTRAINT planes_suscripcion_pkey PRIMARY KEY (id));

-- Table Triggers

create trigger set_fecha_actualizacion_planes before
update
    on
    admin_platform.planes_suscripcion for each row execute function admin_platform.tg_set_fecha_actualizacion_generic();

-- Permissions

ALTER TABLE admin_platform.planes_suscripcion OWNER TO postgres;
GRANT ALL ON TABLE admin_platform.planes_suscripcion TO postgres;


-- admin_platform.tenants definition

-- Drop table

-- DROP TABLE admin_platform.tenants;

CREATE TABLE admin_platform.tenants ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, nombre text NOT NULL, nit text NULL, email_contacto text NOT NULL, telefono_contacto text NULL, direccion text NULL, estado bool DEFAULT true NOT NULL, fecha_creacion timestamp DEFAULT now() NOT NULL, passwordhash text NOT NULL, ultimo_ingreso timestamp NULL, esquema text NOT NULL, estado_suscripcion admin_platform.tenant_billing_status_enum DEFAULT 'active'::admin_platform.tenant_billing_status_enum NOT NULL, plan_suscripcion text DEFAULT 'base'::text NOT NULL, proveedor_pago text NULL, id_cliente_pasarela text NULL, id_suscripcion_pasarela text NULL, periodo_inicio timestamptz NULL, periodo_fin timestamptz NULL, gracia_hasta timestamptz NULL, ultimo_pago_en timestamptz NULL, estado_suscripcion_actualizado_en timestamptz DEFAULT now() NOT NULL, notas_suscripcion text NULL, CONSTRAINT chk_tenants_periodo_suscripcion_range CHECK (((periodo_inicio IS NULL) OR (periodo_fin IS NULL) OR (periodo_fin >= periodo_inicio))), CONSTRAINT tenants_pkey PRIMARY KEY (id));
CREATE INDEX idx_tenants_estado_suscripcion ON admin_platform.tenants USING btree (estado_suscripcion);
CREATE INDEX idx_tenants_gracia_hasta ON admin_platform.tenants USING btree (gracia_hasta) WHERE (gracia_hasta IS NOT NULL);
CREATE INDEX idx_tenants_periodo_fin ON admin_platform.tenants USING btree (periodo_fin) WHERE (periodo_fin IS NOT NULL);
CREATE UNIQUE INDEX ux_tenants_email_contacto_lower ON admin_platform.tenants USING btree (lower(email_contacto));
CREATE UNIQUE INDEX ux_tenants_esquema ON admin_platform.tenants USING btree (esquema);
CREATE UNIQUE INDEX ux_tenants_id_suscripcion_pasarela ON admin_platform.tenants USING btree (id_suscripcion_pasarela) WHERE (id_suscripcion_pasarela IS NOT NULL);
CREATE UNIQUE INDEX ux_tenants_nit ON admin_platform.tenants USING btree (nit);

-- Table Triggers

create trigger set_estado_suscripcion_updated_at_tenants before
update
    on
    admin_platform.tenants for each row execute function admin_platform.tg_tenants_billing_updated_at();

-- Permissions

ALTER TABLE admin_platform.tenants OWNER TO postgres;
GRANT ALL ON TABLE admin_platform.tenants TO postgres;


-- admin_platform.suscripciones_tenants definition

-- Drop table

-- DROP TABLE admin_platform.suscripciones_tenants;

CREATE TABLE admin_platform.suscripciones_tenants ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, tenant_id int4 NOT NULL, plan_id int4 NOT NULL, ciclo_facturacion admin_platform.ciclo_facturacion_enum DEFAULT 'mensual'::admin_platform.ciclo_facturacion_enum NOT NULL, monto_ciclo numeric(12, 2) NOT NULL, moneda text DEFAULT 'COP'::text NOT NULL, fecha_inicio_periodo timestamptz NOT NULL, fecha_fin_periodo timestamptz NOT NULL, proximo_cobro timestamptz NULL, renovacion_automatica bool DEFAULT true NOT NULL, fecha_creacion timestamptz DEFAULT now() NOT NULL, fecha_actualizacion timestamptz DEFAULT now() NOT NULL, CONSTRAINT chk_suscripciones_monto_non_negative CHECK ((monto_ciclo >= (0)::numeric)), CONSTRAINT chk_suscripciones_periodo_valido CHECK ((fecha_fin_periodo > fecha_inicio_periodo)), CONSTRAINT suscripciones_tenants_pkey PRIMARY KEY (id), CONSTRAINT ux_suscripciones_tenants_tenant UNIQUE (tenant_id), CONSTRAINT fk_suscripciones_tenants_plan FOREIGN KEY (plan_id) REFERENCES admin_platform.planes_suscripcion(id), CONSTRAINT fk_suscripciones_tenants_tenant FOREIGN KEY (tenant_id) REFERENCES admin_platform.tenants(id) ON DELETE CASCADE);
CREATE INDEX idx_suscripciones_tenants_proximo_cobro ON admin_platform.suscripciones_tenants USING btree (proximo_cobro) WHERE (proximo_cobro IS NOT NULL);

-- Table Triggers

create trigger set_fecha_actualizacion_suscripciones_tenants before
update
    on
    admin_platform.suscripciones_tenants for each row execute function admin_platform.tg_set_fecha_actualizacion_generic();

-- Permissions

ALTER TABLE admin_platform.suscripciones_tenants OWNER TO postgres;
GRANT ALL ON TABLE admin_platform.suscripciones_tenants TO postgres;


-- admin_platform.facturas_tenants definition

-- Drop table

-- DROP TABLE admin_platform.facturas_tenants;

CREATE TABLE admin_platform.facturas_tenants ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, tenant_id int4 NOT NULL, suscripcion_id int4 NULL, numero_factura text NOT NULL, estado admin_platform.estado_factura_tenant_enum DEFAULT 'pendiente'::admin_platform.estado_factura_tenant_enum NOT NULL, fecha_emision timestamptz DEFAULT now() NOT NULL, fecha_vencimiento timestamptz NULL, periodo_inicio timestamptz NULL, periodo_fin timestamptz NULL, subtotal numeric(12, 2) DEFAULT 0 NOT NULL, impuestos numeric(12, 2) DEFAULT 0 NOT NULL, descuento numeric(12, 2) DEFAULT 0 NOT NULL, total numeric(12, 2) GENERATED ALWAYS AS ((subtotal + impuestos - descuento)) STORED NULL, moneda text DEFAULT 'COP'::text NOT NULL, pagada_en timestamptz NULL, detalle jsonb NULL, fecha_creacion timestamptz DEFAULT now() NOT NULL, CONSTRAINT chk_facturas_montos_non_negative CHECK (((subtotal >= (0)::numeric) AND (impuestos >= (0)::numeric) AND (descuento >= (0)::numeric))), CONSTRAINT facturas_tenants_numero_factura_key UNIQUE (numero_factura), CONSTRAINT facturas_tenants_pkey PRIMARY KEY (id), CONSTRAINT fk_facturas_tenants_suscripcion FOREIGN KEY (suscripcion_id) REFERENCES admin_platform.suscripciones_tenants(id) ON DELETE SET NULL, CONSTRAINT fk_facturas_tenants_tenant FOREIGN KEY (tenant_id) REFERENCES admin_platform.tenants(id) ON DELETE CASCADE);
CREATE INDEX idx_facturas_tenants_estado_vencimiento ON admin_platform.facturas_tenants USING btree (estado, fecha_vencimiento);

-- Permissions

ALTER TABLE admin_platform.facturas_tenants OWNER TO postgres;
GRANT ALL ON TABLE admin_platform.facturas_tenants TO postgres;


-- admin_platform.pagos_tenants definition

-- Drop table

-- DROP TABLE admin_platform.pagos_tenants;

CREATE TABLE admin_platform.pagos_tenants ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, tenant_id int4 NOT NULL, suscripcion_id int4 NULL, factura_id int4 NULL, estado admin_platform.estado_pago_tenant_enum DEFAULT 'pendiente'::admin_platform.estado_pago_tenant_enum NOT NULL, monto numeric(12, 2) NOT NULL, moneda text DEFAULT 'COP'::text NOT NULL, metodo_pago text NULL, proveedor_pago text NULL, referencia_externa text NULL, payload_pasarela jsonb NULL, pagado_en timestamptz NULL, fecha_creacion timestamptz DEFAULT now() NOT NULL, CONSTRAINT chk_pagos_monto_non_negative CHECK ((monto >= (0)::numeric)), CONSTRAINT pagos_tenants_pkey PRIMARY KEY (id), CONSTRAINT fk_pagos_tenants_factura FOREIGN KEY (factura_id) REFERENCES admin_platform.facturas_tenants(id) ON DELETE SET NULL, CONSTRAINT fk_pagos_tenants_suscripcion FOREIGN KEY (suscripcion_id) REFERENCES admin_platform.suscripciones_tenants(id) ON DELETE SET NULL, CONSTRAINT fk_pagos_tenants_tenant FOREIGN KEY (tenant_id) REFERENCES admin_platform.tenants(id) ON DELETE CASCADE);
CREATE INDEX idx_pagos_tenants_estado_pagado_en ON admin_platform.pagos_tenants USING btree (estado, pagado_en);
CREATE INDEX idx_pagos_tenants_tenant ON admin_platform.pagos_tenants USING btree (tenant_id, pagado_en DESC);

-- Permissions

ALTER TABLE admin_platform.pagos_tenants OWNER TO postgres;
GRANT ALL ON TABLE admin_platform.pagos_tenants TO postgres;


-- admin_platform.vw_hechos_pagos_tenants source

CREATE OR REPLACE VIEW admin_platform.vw_hechos_pagos_tenants
AS SELECT pt.id AS pago_id,
    pt.fecha_creacion AS fecha_pago_registro,
    pt.pagado_en,
    pt.estado AS estado_pago,
    pt.monto,
    pt.moneda,
    pt.metodo_pago,
    pt.proveedor_pago,
    pt.referencia_externa,
    t.id AS tenant_id,
    t.nombre AS tenant_nombre,
    t.esquema AS tenant_esquema,
    s.id AS suscripcion_id,
    s.ciclo_facturacion,
    s.proximo_cobro,
    p.codigo AS plan_codigo,
    p.nombre AS plan_nombre,
    f.id AS factura_id,
    f.numero_factura,
    f.estado AS estado_factura,
    f.fecha_emision,
    f.fecha_vencimiento,
    f.total AS total_factura
   FROM admin_platform.pagos_tenants pt
     JOIN admin_platform.tenants t ON t.id = pt.tenant_id
     LEFT JOIN admin_platform.suscripciones_tenants s ON s.id = pt.suscripcion_id
     LEFT JOIN admin_platform.planes_suscripcion p ON p.id = s.plan_id
     LEFT JOIN admin_platform.facturas_tenants f ON f.id = pt.factura_id;

-- Permissions

ALTER TABLE admin_platform.vw_hechos_pagos_tenants OWNER TO postgres;
GRANT ALL ON TABLE admin_platform.vw_hechos_pagos_tenants TO postgres;


-- admin_platform.vw_proximos_cobros_tenants source

CREATE OR REPLACE VIEW admin_platform.vw_proximos_cobros_tenants
AS SELECT t.id AS tenant_id,
    t.nombre AS tenant_nombre,
    t.esquema AS tenant_esquema,
    t.email_contacto,
    s.id AS suscripcion_id,
    p.codigo AS plan_codigo,
    p.nombre AS plan_nombre,
    s.ciclo_facturacion,
    s.monto_ciclo,
    s.moneda,
    s.proximo_cobro,
    t.estado_suscripcion
   FROM admin_platform.suscripciones_tenants s
     JOIN admin_platform.tenants t ON t.id = s.tenant_id
     JOIN admin_platform.planes_suscripcion p ON p.id = s.plan_id
  WHERE s.proximo_cobro IS NOT NULL;

-- Permissions

ALTER TABLE admin_platform.vw_proximos_cobros_tenants OWNER TO postgres;
GRANT ALL ON TABLE admin_platform.vw_proximos_cobros_tenants TO postgres;



-- DROP FUNCTION admin_platform.actualizar_tenant(text, text, text, text, text, text);

CREATE OR REPLACE FUNCTION admin_platform.actualizar_tenant(esquema_actual text, esquema_nuevo text, nuevo_nombre text, nuevo_correo text, nuevo_telefono text, "nueva_contraseña" text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  esquema_existe boolean;
  admin_id integer;
  has_col_correo boolean;
  has_col_nombre boolean;
  has_col_telefono boolean;
  has_col_passwordhash boolean;
  has_col_password boolean;
  has_col_ultima_actualizacion boolean;
  has_col_ultimo_acceso boolean;
  update_sql text;
BEGIN
  IF esquema_actual IS NULL OR btrim(esquema_actual) = '' THEN
    RAISE EXCEPTION 'esquema_actual no puede ser vacío.';
  END IF;

  IF esquema_nuevo IS NULL OR btrim(esquema_nuevo) = '' THEN
    RAISE EXCEPTION 'esquema_nuevo no puede ser vacío.';
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM information_schema.schemata
    WHERE schema_name = esquema_actual
  ) INTO esquema_existe;

  IF NOT esquema_existe THEN
    RAISE EXCEPTION 'El esquema % no existe.', esquema_actual;
  END IF;

  IF esquema_actual <> esquema_nuevo THEN
    IF lower(esquema_nuevo) IN ('public', 'admin_platform', 'tenant_base') THEN
      RAISE EXCEPTION 'No se puede renombrar a un esquema protegido (%).', esquema_nuevo;
    END IF;

    EXECUTE format('ALTER SCHEMA %I RENAME TO %I;', esquema_actual, esquema_nuevo);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = esquema_nuevo
      AND table_name = 'users'
  ) THEN
    RAISE EXCEPTION 'La tabla %.users no existe.', esquema_nuevo;
  END IF;

  EXECUTE format(
    'SELECT id FROM %I.users WHERE rol = ''admin'' ORDER BY id LIMIT 1;',
    esquema_nuevo
  ) INTO admin_id;

  IF admin_id IS NULL THEN
    RAISE EXCEPTION 'No hay usuario admin en %.users.', esquema_nuevo;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = esquema_nuevo AND table_name = 'users' AND column_name = 'correo'
  ) INTO has_col_correo;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = esquema_nuevo AND table_name = 'users' AND column_name = 'nombre'
  ) INTO has_col_nombre;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = esquema_nuevo AND table_name = 'users' AND column_name = 'telefono'
  ) INTO has_col_telefono;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = esquema_nuevo AND table_name = 'users' AND column_name = 'passwordhash'
  ) INTO has_col_passwordhash;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = esquema_nuevo AND table_name = 'users' AND column_name = 'password'
  ) INTO has_col_password;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = esquema_nuevo AND table_name = 'users' AND column_name = 'ultima_actualizacion'
  ) INTO has_col_ultima_actualizacion;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = esquema_nuevo AND table_name = 'users' AND column_name = 'ultimo_acceso'
  ) INTO has_col_ultimo_acceso;

  update_sql := format('UPDATE %I.users SET ', esquema_nuevo);

  IF has_col_correo THEN
    update_sql := update_sql || format('correo = %L, ', nuevo_correo);
  END IF;

  IF has_col_nombre THEN
    update_sql := update_sql || format('nombre = %L, ', nuevo_nombre);
  END IF;

  IF has_col_telefono THEN
    update_sql := update_sql || format('telefono = %L, ', nuevo_telefono);
  END IF;

  IF "nueva_contraseña" IS NOT NULL AND btrim("nueva_contraseña") <> '' THEN
    IF has_col_passwordhash THEN
      update_sql := update_sql || format('passwordhash = %L, ', "nueva_contraseña");
    ELSIF has_col_password THEN
      update_sql := update_sql || format('password = %L, ', "nueva_contraseña");
    END IF;
  END IF;

  IF has_col_ultima_actualizacion THEN
    update_sql := update_sql || 'ultima_actualizacion = now(), ';
  END IF;

  IF has_col_ultimo_acceso THEN
    update_sql := update_sql || 'ultimo_acceso = now(), ';
  END IF;

  update_sql := regexp_replace(update_sql, ',\s*$', '');
  update_sql := update_sql || format(' WHERE id = %s;', admin_id);

  EXECUTE update_sql;

  RAISE NOTICE 'Tenant % actualizado correctamente.', esquema_nuevo;
END;
$function$
;

-- Permissions

ALTER FUNCTION admin_platform.actualizar_tenant(text, text, text, text, text, text) OWNER TO postgres;
GRANT ALL ON FUNCTION admin_platform.actualizar_tenant(text, text, text, text, text, text) TO postgres;

-- DROP FUNCTION admin_platform.crear_tenant(text, text, text, text, text);

CREATE OR REPLACE FUNCTION admin_platform.crear_tenant(nuevo_esquema text, nombre_usuario text, correo_usuario text, telefono_usuario text, "contraseña_usuario" text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  table_rec record;
  enum_col_rec record;
  type_rec record;
  seq_rec record;
  seq_sql text;
  default_rec record;
  new_default text;
  seq_name text;
  fn_record record;
  fn_sql text;
  trigger_record record;
  trigger_sql text;
  fk_record record;
  fk_drop record;
  schema_prefix text;
BEGIN
  IF nuevo_esquema IS NULL OR btrim(nuevo_esquema) = '' THEN
    RAISE EXCEPTION 'El nombre del esquema no puede ser vacío.';
  END IF;

  IF lower(nuevo_esquema) IN ('public', 'admin_platform', 'tenant_base') THEN
    RAISE EXCEPTION 'El esquema % está protegido y no puede usarse.', nuevo_esquema;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.schemata
    WHERE schema_name = nuevo_esquema
  ) THEN
    RAISE EXCEPTION 'El esquema % ya existe.', nuevo_esquema;
  END IF;

  EXECUTE format('CREATE SCHEMA %I;', nuevo_esquema);
  schema_prefix := quote_ident(nuevo_esquema) || '.';

  FOR type_rec IN
    SELECT
      t.typname,
      string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder) AS labels
    FROM pg_type t
    JOIN pg_enum e ON e.enumtypid = t.oid
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'tenant_base'
    GROUP BY t.typname
  LOOP
    EXECUTE format('CREATE TYPE %I.%I AS ENUM (%s);', nuevo_esquema, type_rec.typname, type_rec.labels);
  END LOOP;

  FOR table_rec IN
    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'tenant_base'
    ORDER BY tablename
  LOOP
    EXECUTE format(
      'CREATE TABLE %I.%I (LIKE tenant_base.%I INCLUDING ALL);',
      nuevo_esquema,
      table_rec.tablename,
      table_rec.tablename
    );
  END LOOP;

  FOR enum_col_rec IN
    SELECT
      c.table_name,
      c.column_name,
      c.udt_name
    FROM information_schema.columns c
    WHERE c.table_schema = nuevo_esquema
      AND c.udt_schema = 'tenant_base'
      AND c.data_type = 'USER-DEFINED'
      AND EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE n.nspname = nuevo_esquema
          AND t.typname = c.udt_name
      )
  LOOP
    EXECUTE format(
      'ALTER TABLE %I.%I ALTER COLUMN %I DROP DEFAULT;',
      nuevo_esquema,
      enum_col_rec.table_name,
      enum_col_rec.column_name
    );

    EXECUTE format(
      'ALTER TABLE %I.%I ALTER COLUMN %I TYPE %I.%I USING (%I::text::%I.%I);',
      nuevo_esquema,
      enum_col_rec.table_name,
      enum_col_rec.column_name,
      nuevo_esquema,
      enum_col_rec.udt_name,
      enum_col_rec.column_name,
      nuevo_esquema,
      enum_col_rec.udt_name
    );
  END LOOP;

  FOR seq_rec IN
    SELECT
      sequencename,
      data_type,
      start_value,
      increment_by,
      min_value,
      max_value,
      cache_size,
      cycle
    FROM pg_sequences
    WHERE schemaname = 'tenant_base'
  LOOP
    seq_sql := format(
      'CREATE SEQUENCE IF NOT EXISTS %I.%I AS %s INCREMENT BY %s START WITH %s CACHE %s ',
      nuevo_esquema,
      seq_rec.sequencename,
      seq_rec.data_type,
      seq_rec.increment_by,
      seq_rec.start_value,
      seq_rec.cache_size
    );

    IF seq_rec.min_value IS NULL THEN
      seq_sql := seq_sql || 'NO MINVALUE ';
    ELSE
      seq_sql := seq_sql || format('MINVALUE %s ', seq_rec.min_value);
    END IF;

    IF seq_rec.max_value IS NULL THEN
      seq_sql := seq_sql || 'NO MAXVALUE ';
    ELSE
      seq_sql := seq_sql || format('MAXVALUE %s ', seq_rec.max_value);
    END IF;

    IF seq_rec.cycle THEN
      seq_sql := seq_sql || 'CYCLE;';
    ELSE
      seq_sql := seq_sql || 'NO CYCLE;';
    END IF;

    EXECUTE seq_sql;
  END LOOP;

  FOR default_rec IN
    SELECT table_name, column_name, column_default
    FROM information_schema.columns
    WHERE table_schema = nuevo_esquema
      AND column_default LIKE '%tenant_base.%'
  LOOP
    new_default := replace(default_rec.column_default, 'tenant_base.', schema_prefix);

    EXECUTE format(
      'ALTER TABLE %I.%I ALTER COLUMN %I SET DEFAULT %s;',
      nuevo_esquema,
      default_rec.table_name,
      default_rec.column_name,
      new_default
    );

    SELECT pg_get_serial_sequence(format('%I.%I', nuevo_esquema, default_rec.table_name), default_rec.column_name)
    INTO seq_name;

    IF seq_name IS NOT NULL THEN
      EXECUTE format(
        'ALTER SEQUENCE %s OWNED BY %I.%I.%I;',
        seq_name,
        nuevo_esquema,
        default_rec.table_name,
        default_rec.column_name
      );
    END IF;
  END LOOP;

  FOR fn_record IN
    SELECT
      p.oid,
      format('%I.%I', n.nspname, p.proname) AS qualified_name,
      pg_get_functiondef(p.oid) AS definition
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'tenant_base'
      AND p.prokind = 'f'
  LOOP
    fn_sql := replace(fn_record.definition, 'tenant_base.', schema_prefix);
    fn_sql := regexp_replace(
      fn_sql,
      'CREATE\s+OR\s+REPLACE\s+FUNCTION\s+tenant_base\.',
      'CREATE OR REPLACE FUNCTION ' || quote_ident(nuevo_esquema) || '.',
      1,
      1,
      'i'
    );
    EXECUTE fn_sql;
  END LOOP;

  FOR trigger_record IN
    SELECT
      tg.oid,
      tg.tgname,
      rel.relname AS table_name,
      pg_get_triggerdef(tg.oid, true) AS definition
    FROM pg_trigger tg
    JOIN pg_class rel ON rel.oid = tg.tgrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE nsp.nspname = 'tenant_base'
      AND tg.tgisinternal = false
  LOOP
    trigger_sql := replace(trigger_record.definition, 'tenant_base.', schema_prefix) || ';';
    EXECUTE trigger_sql;
  END LOOP;

  FOR fk_drop IN
    SELECT con.conname AS constraint_name, rel.relname AS table_name
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE nsp.nspname = nuevo_esquema
      AND con.contype = 'f'
  LOOP
    EXECUTE format(
      'ALTER TABLE %I.%I DROP CONSTRAINT %I;',
      nuevo_esquema,
      fk_drop.table_name,
      fk_drop.constraint_name
    );
  END LOOP;

  FOR fk_record IN
    SELECT
      con.conname AS constraint_name,
      rel.relname AS table_name,
      confrel.relname AS foreign_table_name,
      string_agg(quote_ident(att.attname), ', ' ORDER BY k.ord) AS local_columns,
      string_agg(quote_ident(confatt.attname), ', ' ORDER BY k.ord) AS foreign_columns,
      CASE con.confdeltype
        WHEN 'r' THEN 'RESTRICT'
        WHEN 'c' THEN 'CASCADE'
        WHEN 'n' THEN 'SET NULL'
        WHEN 'd' THEN 'SET DEFAULT'
        ELSE 'NO ACTION'
      END AS on_delete_action,
      CASE con.confupdtype
        WHEN 'r' THEN 'RESTRICT'
        WHEN 'c' THEN 'CASCADE'
        WHEN 'n' THEN 'SET NULL'
        WHEN 'd' THEN 'SET DEFAULT'
        ELSE 'NO ACTION'
      END AS on_update_action
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    JOIN pg_class confrel ON confrel.oid = con.confrelid
    JOIN LATERAL unnest(con.conkey) WITH ORDINALITY AS k(attnum, ord) ON true
    JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = k.attnum
    JOIN LATERAL unnest(con.confkey) WITH ORDINALITY AS fk(attnum, ord) ON fk.ord = k.ord
    JOIN pg_attribute confatt ON confatt.attrelid = con.confrelid AND confatt.attnum = fk.attnum
    WHERE nsp.nspname = 'tenant_base'
      AND con.contype = 'f'
    GROUP BY con.conname, rel.relname, confrel.relname, con.confdeltype, con.confupdtype
    ORDER BY rel.relname, con.conname
  LOOP
    EXECUTE format(
      'ALTER TABLE %I.%I ADD CONSTRAINT %I FOREIGN KEY (%s) REFERENCES %I.%I (%s) ON DELETE %s ON UPDATE %s;',
      nuevo_esquema,
      fk_record.table_name,
      fk_record.constraint_name,
      fk_record.local_columns,
      nuevo_esquema,
      fk_record.foreign_table_name,
      fk_record.foreign_columns,
      fk_record.on_delete_action,
      fk_record.on_update_action
    );
  END LOOP;

  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = nuevo_esquema
      AND table_name = 'users'
  ) THEN
    BEGIN
      EXECUTE format(
        'INSERT INTO %I.users (correo, passwordhash, rol, estado, fecha_creacion, ultima_actualizacion)
         VALUES ($1, $2, ''admin''::%I.user_role_enum, ''activo''::%I.user_status_enum, now(), now());',
        nuevo_esquema,
        nuevo_esquema,
        nuevo_esquema
      ) USING correo_usuario, "contraseña_usuario";
    EXCEPTION WHEN OTHERS THEN
      EXECUTE format(
        'INSERT INTO %I.users (correo, passwordhash, rol, estado)
         VALUES ($1, $2, ''admin''::%I.user_role_enum, ''activo''::%I.user_status_enum);',
        nuevo_esquema,
        nuevo_esquema,
        nuevo_esquema
      ) USING correo_usuario, "contraseña_usuario";
    END;
  ELSE
    RAISE EXCEPTION 'No existe %.users en el esquema creado.', nuevo_esquema;
  END IF;

  RAISE NOTICE 'Tenant % creado correctamente desde tenant_base.', nuevo_esquema;
END;
$function$
;

-- Permissions

ALTER FUNCTION admin_platform.crear_tenant(text, text, text, text, text) OWNER TO postgres;
GRANT ALL ON FUNCTION admin_platform.crear_tenant(text, text, text, text, text) TO postgres;

-- DROP FUNCTION admin_platform.eliminar_tenant(text);

CREATE OR REPLACE FUNCTION admin_platform.eliminar_tenant(esquema_a_eliminar text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF esquema_a_eliminar IS NULL OR btrim(esquema_a_eliminar) = '' THEN
    RAISE EXCEPTION 'El nombre del esquema no puede ser vacío.';
  END IF;

  IF lower(esquema_a_eliminar) IN ('tenant_base', 'public', 'admin_platform') THEN
    RAISE EXCEPTION 'El esquema % está protegido y no puede eliminarse.', esquema_a_eliminar;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.schemata
    WHERE schema_name = esquema_a_eliminar
  ) THEN
    RAISE EXCEPTION 'El esquema % no existe.', esquema_a_eliminar;
  END IF;

  EXECUTE format('DROP SCHEMA %I CASCADE;', esquema_a_eliminar);
END;
$function$
;

-- Permissions

ALTER FUNCTION admin_platform.eliminar_tenant(text) OWNER TO postgres;
GRANT ALL ON FUNCTION admin_platform.eliminar_tenant(text) TO postgres;

-- DROP FUNCTION admin_platform.fn_intervalo_por_ciclo(admin_platform.ciclo_facturacion_enum);

CREATE OR REPLACE FUNCTION admin_platform.fn_intervalo_por_ciclo(p_ciclo admin_platform.ciclo_facturacion_enum)
 RETURNS interval
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF p_ciclo = 'mensual' THEN
    RETURN interval '1 month';
  ELSIF p_ciclo = 'trimestral' THEN
    RETURN interval '3 months';
  END IF;

  RETURN interval '1 year';
END;
$function$
;

-- Permissions

ALTER FUNCTION admin_platform.fn_intervalo_por_ciclo(admin_platform.ciclo_facturacion_enum) OWNER TO postgres;
GRANT ALL ON FUNCTION admin_platform.fn_intervalo_por_ciclo(admin_platform.ciclo_facturacion_enum) TO postgres;

-- DROP FUNCTION admin_platform.registrar_pago_tenant(int4, numeric, text, text, text, text, admin_platform.ciclo_facturacion_enum, timestamptz);

CREATE OR REPLACE FUNCTION admin_platform.registrar_pago_tenant(p_tenant_id integer, p_monto numeric, p_moneda text DEFAULT 'COP'::text, p_metodo_pago text DEFAULT NULL::text, p_proveedor_pago text DEFAULT NULL::text, p_referencia_externa text DEFAULT NULL::text, p_ciclo admin_platform.ciclo_facturacion_enum DEFAULT NULL::admin_platform.ciclo_facturacion_enum, p_fecha_pago timestamp with time zone DEFAULT now())
 RETURNS TABLE(pago_id integer, factura_id integer, suscripcion_id integer, tenant_id integer, estado_suscripcion admin_platform.tenant_billing_status_enum, proximo_cobro timestamp with time zone)
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_suscripcion admin_platform.suscripciones_tenants%ROWTYPE;
  v_ciclo admin_platform.ciclo_facturacion_enum;
  v_plan admin_platform.planes_suscripcion%ROWTYPE;
  v_numero_factura text;
  v_factura_id int;
  v_pago_id int;
  v_inicio_periodo timestamptz;
  v_fin_periodo timestamptz;
  v_monto_ciclo numeric(12,2);
BEGIN
  IF p_monto <= 0 THEN
    RAISE EXCEPTION 'El monto del pago debe ser mayor a 0.';
  END IF;

  SELECT *
  INTO v_suscripcion
  FROM admin_platform.suscripciones_tenants s
  WHERE s.tenant_id = p_tenant_id
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No existe suscripción para tenant_id=%.', p_tenant_id;
  END IF;

  SELECT *
  INTO v_plan
  FROM admin_platform.planes_suscripcion p
  WHERE p.id = v_suscripcion.plan_id
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No existe plan para la suscripción tenant_id=%.', p_tenant_id;
  END IF;

  v_ciclo := COALESCE(p_ciclo, v_suscripcion.ciclo_facturacion);

  v_monto_ciclo := CASE v_ciclo
    WHEN 'mensual' THEN v_plan.precio_mensual
    WHEN 'trimestral' THEN v_plan.precio_trimestral
    ELSE v_plan.precio_anual
  END;

  v_inicio_periodo := CASE
    WHEN v_suscripcion.fecha_fin_periodo > p_fecha_pago THEN v_suscripcion.fecha_fin_periodo
    ELSE p_fecha_pago
  END;

  v_fin_periodo := v_inicio_periodo + admin_platform.fn_intervalo_por_ciclo(v_ciclo);

  v_numero_factura := format('FAC-%s-%s', to_char(now(), 'YYYYMMDDHH24MISSUS'), p_tenant_id);

  INSERT INTO admin_platform.facturas_tenants (
    tenant_id,
    suscripcion_id,
    numero_factura,
    estado,
    fecha_emision,
    fecha_vencimiento,
    periodo_inicio,
    periodo_fin,
    subtotal,
    impuestos,
    descuento,
    moneda,
    pagada_en,
    detalle
  )
  VALUES (
    p_tenant_id,
    v_suscripcion.id,
    v_numero_factura,
    'pagada',
    p_fecha_pago,
    p_fecha_pago,
    v_inicio_periodo,
    v_fin_periodo,
    p_monto,
    0,
    0,
    COALESCE(NULLIF(p_moneda, ''), v_suscripcion.moneda),
    p_fecha_pago,
    jsonb_build_object('origen', 'manual_o_pasarela', 'ciclo_aplicado', v_ciclo)
  )
  RETURNING id INTO v_factura_id;

  INSERT INTO admin_platform.pagos_tenants (
    tenant_id,
    suscripcion_id,
    factura_id,
    estado,
    monto,
    moneda,
    metodo_pago,
    proveedor_pago,
    referencia_externa,
    pagado_en,
    payload_pasarela
  )
  VALUES (
    p_tenant_id,
    v_suscripcion.id,
    v_factura_id,
    'aprobado',
    p_monto,
    COALESCE(NULLIF(p_moneda, ''), v_suscripcion.moneda),
    p_metodo_pago,
    p_proveedor_pago,
    p_referencia_externa,
    p_fecha_pago,
    jsonb_build_object('referencia', p_referencia_externa)
  )
  RETURNING id INTO v_pago_id;

  UPDATE admin_platform.suscripciones_tenants
  SET
    ciclo_facturacion = v_ciclo,
    monto_ciclo = v_monto_ciclo,
    moneda = COALESCE(NULLIF(p_moneda, ''), v_suscripcion.moneda),
    fecha_inicio_periodo = v_inicio_periodo,
    fecha_fin_periodo = v_fin_periodo,
    proximo_cobro = v_fin_periodo,
    fecha_actualizacion = now()
  WHERE id = v_suscripcion.id;

  UPDATE admin_platform.tenants
  SET
    estado_suscripcion = 'active',
    gracia_hasta = NULL,
    ultimo_pago_en = p_fecha_pago
  WHERE id = p_tenant_id;

  RETURN QUERY
  SELECT
    v_pago_id,
    v_factura_id,
    v_suscripcion.id,
    p_tenant_id,
    'active'::admin_platform.tenant_billing_status_enum,
    v_fin_periodo;
END;
$function$
;

-- Permissions

ALTER FUNCTION admin_platform.registrar_pago_tenant(int4, numeric, text, text, text, text, admin_platform.ciclo_facturacion_enum, timestamptz) OWNER TO postgres;
GRANT ALL ON FUNCTION admin_platform.registrar_pago_tenant(int4, numeric, text, text, text, text, admin_platform.ciclo_facturacion_enum, timestamptz) TO postgres;

-- DROP FUNCTION admin_platform.sincronizar_estado_suscripciones_tenants(int4, int4);

CREATE OR REPLACE FUNCTION admin_platform.sincronizar_estado_suscripciones_tenants(p_dias_gracia integer DEFAULT 5, p_dias_para_pausa integer DEFAULT 30)
 RETURNS TABLE(total_actualizados integer, a_past_due integer, a_unpaid integer, a_paused integer)
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_past_due int := 0;
  v_unpaid int := 0;
  v_paused int := 0;
BEGIN
  UPDATE admin_platform.tenants t
  SET
    estado_suscripcion = 'past_due',
    gracia_hasta = now() + make_interval(days => p_dias_gracia)
  FROM admin_platform.suscripciones_tenants s
  WHERE s.tenant_id = t.id
    AND t.estado = true
    AND t.estado_suscripcion IN ('active', 'trialing')
    AND s.proximo_cobro IS NOT NULL
    AND s.proximo_cobro < now();
  GET DIAGNOSTICS v_past_due = ROW_COUNT;

  UPDATE admin_platform.tenants t
  SET estado_suscripcion = 'unpaid'
  WHERE t.estado_suscripcion = 'past_due'
    AND t.gracia_hasta IS NOT NULL
    AND t.gracia_hasta < now();
  GET DIAGNOSTICS v_unpaid = ROW_COUNT;

  UPDATE admin_platform.tenants t
  SET estado_suscripcion = 'paused'
  FROM admin_platform.suscripciones_tenants s
  WHERE s.tenant_id = t.id
    AND t.estado_suscripcion = 'unpaid'
    AND s.proximo_cobro IS NOT NULL
    AND s.proximo_cobro < now() - make_interval(days => p_dias_para_pausa);
  GET DIAGNOSTICS v_paused = ROW_COUNT;

  RETURN QUERY
  SELECT v_past_due + v_unpaid + v_paused, v_past_due, v_unpaid, v_paused;
END;
$function$
;

-- Permissions

ALTER FUNCTION admin_platform.sincronizar_estado_suscripciones_tenants(int4, int4) OWNER TO postgres;
GRANT ALL ON FUNCTION admin_platform.sincronizar_estado_suscripciones_tenants(int4, int4) TO postgres;

-- DROP FUNCTION admin_platform.tenant_can_login(int4, timestamptz);

CREATE OR REPLACE FUNCTION admin_platform.tenant_can_login(p_tenant_id integer, p_now timestamp with time zone DEFAULT now())
 RETURNS TABLE(can_login boolean, reason text)
 LANGUAGE plpgsql
AS $function$
DECLARE
  tenant_record admin_platform.tenants%ROWTYPE;
BEGIN
  SELECT *
  INTO tenant_record
  FROM admin_platform.tenants t
  WHERE t.id = p_tenant_id
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN QUERY SELECT false, 'tenant_not_found'::text;
    RETURN;
  END IF;

  IF tenant_record.estado = false THEN
    RETURN QUERY SELECT false, 'tenant_inactive'::text;
    RETURN;
  END IF;

  IF tenant_record.estado_suscripcion IN ('active', 'trialing') THEN
    RETURN QUERY SELECT true, 'ok'::text;
    RETURN;
  END IF;

  IF tenant_record.estado_suscripcion = 'past_due' THEN
    IF tenant_record.gracia_hasta IS NOT NULL AND tenant_record.gracia_hasta >= p_now THEN
      RETURN QUERY SELECT true, 'grace_period'::text;
      RETURN;
    END IF;

    RETURN QUERY SELECT false, 'payment_past_due'::text;
    RETURN;
  END IF;

  IF tenant_record.estado_suscripcion = 'paused' THEN
    RETURN QUERY SELECT false, 'subscription_paused'::text;
    RETURN;
  END IF;

  IF tenant_record.estado_suscripcion = 'canceled' THEN
    RETURN QUERY SELECT false, 'subscription_canceled'::text;
    RETURN;
  END IF;

  IF tenant_record.estado_suscripcion = 'unpaid' THEN
    RETURN QUERY SELECT false, 'subscription_unpaid'::text;
    RETURN;
  END IF;

  RETURN QUERY SELECT false, 'subscription_incomplete'::text;
END;
$function$
;

-- Permissions

ALTER FUNCTION admin_platform.tenant_can_login(int4, timestamptz) OWNER TO postgres;
GRANT ALL ON FUNCTION admin_platform.tenant_can_login(int4, timestamptz) TO postgres;

-- DROP FUNCTION admin_platform.tg_admin_users_updated_at();

CREATE OR REPLACE FUNCTION admin_platform.tg_admin_users_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.fecha_actualizacion := now();
  RETURN NEW;
END$function$
;

-- Permissions

ALTER FUNCTION admin_platform.tg_admin_users_updated_at() OWNER TO postgres;
GRANT ALL ON FUNCTION admin_platform.tg_admin_users_updated_at() TO postgres;

-- DROP FUNCTION admin_platform.tg_set_fecha_actualizacion_generic();

CREATE OR REPLACE FUNCTION admin_platform.tg_set_fecha_actualizacion_generic()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.fecha_actualizacion := now();
  RETURN NEW;
END;
$function$
;

-- Permissions

ALTER FUNCTION admin_platform.tg_set_fecha_actualizacion_generic() OWNER TO postgres;
GRANT ALL ON FUNCTION admin_platform.tg_set_fecha_actualizacion_generic() TO postgres;

-- DROP FUNCTION admin_platform.tg_tenants_billing_updated_at();

CREATE OR REPLACE FUNCTION admin_platform.tg_tenants_billing_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.estado_suscripcion IS DISTINCT FROM OLD.estado_suscripcion THEN
    NEW.estado_suscripcion_actualizado_en := now();
  END IF;

  RETURN NEW;
END;
$function$
;

-- Permissions

ALTER FUNCTION admin_platform.tg_tenants_billing_updated_at() OWNER TO postgres;
GRANT ALL ON FUNCTION admin_platform.tg_tenants_billing_updated_at() TO postgres;


-- Permissions

GRANT ALL ON SCHEMA admin_platform TO postgres;